# ML-03 — Frame Your Lane as an ML Task

[![Open In Colab](https://colab.research.google.com/assets/colab-badge.svg)](https://colab.research.google.com/github/Srichandana2404/flyrank-ml-track/blob/main/work/notebooks/w02_ml_task_framing.ipynb?flush_cache=true)

This skeleton is yours to fill. Work the sections **in order** — each one has a one-line hint. Simple words, honest numbers.

> Working with an AI assistant? Tell it to read `skills/README.md` first and load the one skill this assignment names on its card.

## 1. My lane as an ML task (type)

*Classification, clustering, ranking, or scoring — which one, and why?

Ranking — my goal is to rank website pages by how urgently they need a refresh. This helps content managers prioritize updates based on engagement signals rather than guesswork.

In [ ]:
# This cell is for CODE (numbers, a query, a check).
# Write your text answer in the cell ABOVE this one — typing sentences here breaks Run All.

## 2. Target or proxy

*What would you predict? Where does that label come from — observed outcome or a defined rule?*

The target is engagement decay — measured by a drop in CTR or impressions over time. This label comes from observed performance data, not a fixed rule.

In [ ]:
# This cell is for CODE (numbers, a query, a check).
# Write your text answer in the cell ABOVE this one — typing sentences here breaks Run All.

## 3. Success metric

*One metric you can defend. What number means 'good'?*

NDCG (Normalized Discounted Cumulative Gain) — it measures how well the model ranks pages compared to the ideal order. A higher NDCG means the ranking aligns with true engagement priorities.

In [ ]:
# This cell is for CODE (numbers, a query, a check).
# Write your text answer in the cell ABOVE this one — typing sentences here breaks Run All.

## 4. The unit of analysis, as a real dataframe

*Load your lane's slice and show it: one row = one what?*

One row = one page. Each page has metrics like impressions, CTR, last refresh date, and engagement trend.

In [1]:
# This cell is for CODE (numbers, a query, a check).
# Write your text answer in the cell ABOVE this one — typing sentences here breaks Run All.
import pandas as pd

data = {
    'page_id': [1, 2, 3, 4, 5],
    'impressions': [1200, 950, 800, 600, 400],
    'ctr': [0.12, 0.10, 0.08, 0.05, 0.03],
    'last_refresh_days': [30, 60, 90, 120, 150]
}

df = pd.DataFrame(data)
df.head()

   page_id  impressions   ctr  last_refresh_days
0        1         1200  0.12                 30
1        2          950  0.10                 60
2        3          800  0.08                 90
3        4          600  0.05                120
4        5          400  0.03                150

In [2]:
df['ctr_drop'] = df['ctr'].diff().fillna(0)
df.head()

   page_id  impressions   ctr  last_refresh_days  ctr_drop
0        1         1200  0.12                 30      0.00
1        2          950  0.10                 60     -0.02
2        3          800  0.08                 90     -0.02
3        4          600  0.05                120     -0.03
4        5          400  0.03                150     -0.02

## 5. Why ML beats a fixed rule here

*What makes the pattern too messy for an if-statement?*

Fixed rules like “refresh every 6 months” or “update pages with CTR below 5%” are too simplistic. Engagement patterns vary by page type, audience, and seasonality. For example, some pages drop quickly after a campaign ends, while evergreen pages hold steady for years. An if‑statement can’t capture these messy, overlapping signals. ML can learn from multiple features — impressions, CTR trends, last refresh date, and content category — to predict which pages are truly decaying. This makes the refresh decision adaptive instead of rigid.

In [ ]:
# This cell is for CODE (numbers, a query, a check).
# Write your text answer in the cell ABOVE this one — typing sentences here breaks Run All.

## Self-check

Before you submit, confirm each line honestly:

- [ ] Every section above is filled — markdown thinking AND the code that backs it
- [ ] The notebook runs top to bottom with no errors (Runtime → Run all)
- [ ] No client names, URLs, or private queries anywhere
- [ ] My claims use careful words: observed, measured, directional, decision-support
- [ ] Committed to my repo under `work/notebooks/` — then submit your repo URL on the card. Done.